FROM node:20

WORKDIR /app

# Instalar dependências primeiro para aproveitar o cache do Docker
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copiar o restante do código
COPY . .

# Expor a porta do Vite
EXPOSE 5174

# Rodar o Vite com host 0.0.0.0 para ser acessível fora do container
CMD ["npm", "run", "dev", "--", "--host"]
